import './styles.css';
const API=(import.meta.env.VITE_API_BASE_URL as string|undefined)??'';const DEV_EMAIL=import.meta.env.VITE_DEV_USER_EMAIL as string|undefined;
async function api(path:string,init:RequestInit={}){const headers=new Headers(init.headers);if(init.body&&!headers.has('content-type')&&!(init.body instanceof FormData))headers.set('content-type','application/json');if(DEV_EMAIL)headers.set('x-yrak-user-email',DEV_EMAIL);const r=await fetch(`${API}${path}`,{...init,headers});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error??`HTTP ${r.status}`);return data;}
const app=document.querySelector<HTMLDivElement>('#app')!;app.innerHTML=`<div class="shell"><aside class="sidebar"><h1>YRAK Coberturas</h1><button data-view="dashboard">Resumen</button><button data-view="employees">Personal</button><button data-view="coverages">Coberturas</button><button data-view="competition">Concursos</button><button data-view="config">Configuración</button></aside><main class="main" id="view"></main></div>`;const view=document.querySelector<HTMLDivElement>('#view')!;
async function dashboard(){const [e,c]=await Promise.all([api('/v1/employees'),api('/v1/coverage-cases')]);view.innerHTML=`<h2>Resumen</h2><div class="cards"><div class="card"><div class="muted">Personal</div><div class="metric">${e.items.length}</div></div><div class="card"><div class="muted">Coberturas</div><div class="metric">${c.items.length}</div></div><div class="card"><div class="muted">Activas/programadas</div><div class="metric">${c.items.filter((x:any)=>['ACTIVE','SCHEDULED'].includes(x.status)).length}</div></div></div><h3>Últimas coberturas</h3>${table(c.items,['id','target_level_id','starts_on','ends_on','process_type','status'])}`;}
function table(items:any[],keys:string[]){return `<table><thead><tr>${keys.map(k=>`<th>${k}</th>`).join('')}</tr></thead><tbody>${items.map(x=>`<tr>${keys.map(k=>`<td>${x[k]??''}</td>`).join('')}</tr>`).join('')}</tbody></table>`;}
async function employees(){const data=await api('/v1/employees');view.innerHTML=`<h2>Personal</h2><div class="panel"><p class="muted">La carga masiva usa POST /v1/import/employees. El formulario individual se habilita con los IDs reales de grupo y nivel.</p><form id="employee"><div class="grid"><div><label>Número</label><input name="employeeNumber" required><label>Nombre</label><input name="name" required><label>Email</label><input name="email"></div><div><label>Group ID</label><input name="groupId" required><label>Base Level ID</label><input name="baseLevelId" required><label>Antigüedad</label><input name="seniorityDate" type="date"></div></div><button class="primary">Guardar</button><div class="error" id="employee-error"></div></form></div><h3>Registros</h3>${table(data.items,['employee_number','name','group_id','base_level_id','active'])}`;document.querySelector<HTMLFormElement>('#employee')!.onsubmit=async ev=>{ev.preventDefault();const f=new FormData(ev.currentTarget);try{await api('/v1/employees',{method:'POST',body:JSON.stringify(Object.fromEntries(f))});await employees();}catch(e){document.querySelector('#employee-error')!.textContent=String(e);}};}
async function coverages(){const data=await api('/v1/coverage-cases');view.innerHTML=`<h2>Coberturas</h2><div class="panel"><form id="coverage"><div class="grid"><div><label>Group ID</label><input name="groupId" required><label>Target Level ID</label><input name="targetLevelId" required></div><div><label>Inicio</label><input name="startDate" type="date" required><label>Fin</label><input name="endDate" type="date" required><label>Motivo</label><input name="reason"></div></div><button class="primary">Crear expediente</button><div class="error" id="coverage-error"></div></form></div><h3>Expedientes</h3>${table(data.items,['id','target_level_id','effective_days','process_type','status'])}`;document.querySelector<HTMLFormElement>('#coverage')!.onsubmit=async ev=>{ev.preventDefault();const f=new FormData(ev.currentTarget);try{await api('/v1/coverage-cases',{method:'POST',body:JSON.stringify(Object.fromEntries(f))});await coverages();}catch(e){document.querySelector('#coverage-error')!.textContent=String(e);}};}
async function competition(){view.innerHTML=`<h2>Concursos</h2><div class="panel"><p>Flujo disponible por API:</p><ol><li>POST <code>/v1/competitions/cases/:caseId/evaluate</code></li><li>PUT <code>/v1/competitions/:competitionId/candidates/:candidateId/score</code></li><li>POST <code>/v1/competitions/:competitionId/rank</code></li><li>POST <code>/v1/competitions/:competitionId/award</code></li></ol><p class="muted">El resultado es determinista; ningún agente de IA decide el ganador.</p></div>`;}
async function config(){view.innerHTML=`<h2>Configuración</h2><div class="grid"><div class="panel"><h3>Regla fija</h3><p><strong>1–5 días:</strong> rotación.</p><p><strong>6+ días:</strong> requisitos + examen.</p></div><div class="panel"><h3>Política por grupo</h3><p>Configura días naturales, laborales o turnos mediante <code>/v1/policies/groups/:groupId/coverage</code>.</p></div></div>`;}
const views:any={dashboard,employees,coverages,competition,config};document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>views[(b as HTMLElement).dataset.view!]().catch((e:any)=>view.innerHTML=`<div class="error">${e}</div>`)));dashboard().catch(e=>view.innerHTML=`<div class="error">${e}</div>`);
