export function adminHtml(): string {
  return `<!doctype html>
<html lang="es-MX">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>YRAK Coberturas</title>
  <style>
    :root{font-family:Inter,ui-sans-serif,system-ui,-apple-system,sans-serif;color:#182235;background:#f3f5f8;line-height:1.45}
    *{box-sizing:border-box}body{margin:0}.shell{display:grid;grid-template-columns:250px minmax(0,1fr);min-height:100vh}
    aside{background:#101827;color:#fff;padding:24px 18px;position:sticky;top:0;height:100vh}aside h1{font-size:20px;margin:0 8px 6px}aside p{font-size:12px;color:#9ca3af;margin:0 8px 24px}
    nav button{width:100%;display:block;text-align:left;border:0;background:transparent;color:#d1d5db;padding:11px 12px;border-radius:9px;cursor:pointer;font-size:14px}nav button:hover,nav button.active{background:#273449;color:#fff}
    main{padding:30px;min-width:0}.top{display:flex;justify-content:space-between;gap:20px;align-items:flex-start;margin-bottom:22px}.top h2{margin:0}.muted{color:#667085}.notice{background:#fff7dd;border:1px solid #f4db86;padding:10px 14px;border-radius:10px;font-size:13px}
    .cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:14px}.card,.panel{background:#fff;border:1px solid #e5e9f0;border-radius:14px;box-shadow:0 4px 18px #1822350a}.card{padding:18px}.number{font-size:31px;font-weight:760;margin-top:6px}.panel{padding:18px;margin-top:16px;overflow:auto}.panel h3{margin:0 0 14px}
    table{width:100%;border-collapse:collapse;font-size:13px}th,td{text-align:left;padding:10px;border-bottom:1px solid #edf0f4;vertical-align:top}th{color:#667085;font-weight:650;white-space:nowrap}.badge{display:inline-block;padding:3px 8px;border-radius:999px;background:#edf2f7;font-size:11px}.badge.pending{background:#fff2c8}.badge.active{background:#dff6e8}.badge.error{background:#ffe0e0}
    form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}form .wide{grid-column:1/-1}label{font-size:12px;font-weight:650;color:#485467}input,select,textarea{width:100%;margin-top:5px;border:1px solid #cfd6e2;border-radius:9px;padding:10px;background:#fff;color:#182235}textarea{min-height:80px;resize:vertical}
    button.primary,button.secondary,button.danger{border:0;border-radius:9px;padding:9px 13px;cursor:pointer;font-weight:650}button.primary{background:#175cd3;color:#fff}button.secondary{background:#eef2f7;color:#26364d}button.danger{background:#c93434;color:#fff}.actions{display:flex;gap:8px;flex-wrap:wrap}.empty{padding:26px;text-align:center;color:#667085}.errorbox{white-space:pre-wrap;background:#fff0f0;color:#8b1e1e;padding:12px;border-radius:10px}.hidden{display:none!important}
    .mobile-nav{display:none}.split{display:grid;grid-template-columns:1fr 1fr;gap:16px}.code{font-family:ui-monospace,SFMono-Regular,monospace;font-size:11px;white-space:pre-wrap;max-width:540px}
    @media(max-width:850px){.shell{grid-template-columns:1fr}aside{display:none}.mobile-nav{display:flex;overflow:auto;gap:8px;margin-bottom:16px}.mobile-nav button{white-space:nowrap;border:1px solid #d6dce5;background:#fff;border-radius:9px;padding:8px}main{padding:18px}.split{grid-template-columns:1fr}form{grid-template-columns:1fr}.top{display:block}}
  </style>
</head>
<body>
<div class="shell">
  <aside><h1>YRAK Coberturas</h1><p>SUTERM · operación auditable</p><nav id="desktopNav"></nav></aside>
  <main>
    <div class="mobile-nav" id="mobileNav"></div>
    <div class="top"><div><h2 id="title">Resumen</h2><div class="muted" id="subtitle">Centro de control</div></div><div class="notice">1–5 días: rotación · 6+ días: requisitos y examen · nivel base inmutable</div></div>
    <div id="view"><div class="panel">Cargando…</div></div>
  </main>
</div>
<script>
(function(){
  const pages=[['dashboard','Resumen'],['employees','Personal'],['coverages','Coberturas'],['approvals','Aprobaciones'],['rotations','Rotaciones'],['competitions','Concursos'],['intake','Audios e imágenes'],['configuration','Configuración'],['audit','Auditoría'],['messages','Mensajes']];
  const state={config:null,employees:[]};
  const view=document.getElementById('view');
  const title=document.getElementById('title');
  const subtitle=document.getElementById('subtitle');
  const esc=(value)=>String(value??'').replace(/[&<>"']/g,(char)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const badge=(value)=>'<span class="badge '+(String(value).includes('PENDING')?'pending':String(value).includes('ACTIVE')?'active':String(value).includes('FAILED')?'error':'')+'">'+esc(value)+'</span>';
  function headers(mutating){const h={'content-type':'application/json'};if(location.hostname==='localhost'||location.hostname==='127.0.0.1'){h['x-test-user']='DEV-ADMIN';h['x-test-roles']='ADMIN';h['x-test-organization']='ORG-DEMO';}if(mutating)h['idempotency-key']=crypto.randomUUID();return h;}
  async function api(path,options={}){const opts={...options,headers:{...headers(Boolean(options.method&&options.method!=='GET')),...(options.headers||{})}};if(options.body instanceof FormData){delete opts.headers['content-type'];}const response=await fetch('/api/v1'+path,opts);const text=await response.text();let data={};try{data=text?JSON.parse(text):{};}catch{data={raw:text};}if(!response.ok)throw new Error((data.message||data.error||response.status)+'\n'+JSON.stringify(data,null,2));return data;}
  const table=(columns,rows)=>rows.length?'<table><thead><tr>'+columns.map(c=>'<th>'+esc(c[0])+'</th>').join('')+'</tr></thead><tbody>'+rows.map(row=>'<tr>'+columns.map(c=>'<td>'+c[1](row)+'</td>').join('')+'</tr>').join('')+'</tbody></table>':'<div class="empty">Sin registros</div>';
  function nav(){const html=pages.map(([id,label])=>'<button data-page="'+id+'">'+label+'</button>').join('');document.getElementById('desktopNav').innerHTML=html;document.getElementById('mobileNav').innerHTML=html;document.querySelectorAll('[data-page]').forEach(button=>button.onclick=()=>load(button.dataset.page));}
  async function ensureBase(){if(!state.config)state.config=await api('/configuration-summary');if(!state.employees.length)state.employees=(await api('/employees')).items||[];}
  function showError(error){view.innerHTML='<div class="errorbox">'+esc(error.message||error)+'</div>';}
  async function dashboard(){const data=await api('/dashboard');view.innerHTML='<div class="cards">'+[['Coberturas activas',data.activeCoverages],['Concursos abiertos',data.openCompetitions],['Requisitos con incidencia',data.requirementIssues],['Aprobaciones pendientes',data.pendingApprovals]].map(item=>'<div class="card"><div class="muted">'+item[0]+'</div><div class="number">'+esc(item[1])+'</div></div>').join('')+'</div><div class="panel"><h3>Controles esenciales</h3><p>Las decisiones se calculan por reglas deterministas. Los agentes únicamente extraen datos, generan borradores y explican el historial.</p></div>';}
  async function employees(){await ensureBase();const levels=state.config.levels||[];const groups=state.config.groups||[];view.innerHTML='<div class="split"><div class="panel"><h3>Agregar persona</h3><form id="employeeForm"><label>Número<input name="employeeNumber" required></label><label>Nombre<input name="name" required></label><label>Correo<input name="email" type="email"></label><label>Antigüedad<input name="seniorityDate" type="date" required></label><label>Grupo<select name="groupId" required>'+groups.map(g=>'<option value="'+esc(g.id)+'">'+esc(g.name)+'</option>').join('')+'</select></label><label>Nivel base<select name="baseLevelId" required>'+levels.map(l=>'<option value="'+esc(l.id)+'">'+esc(l.name)+'</option>').join('')+'</select></label><div class="wide"><button class="primary">Guardar</button></div></form></div><div class="panel"><h3>Personal</h3>'+table([['Número',r=>esc(r.employee_number)],['Nombre',r=>esc(r.name)],['Nivel',r=>esc(r.base_level_id)],['Estado',r=>badge(r.active?'ACTIVO':'INACTIVO')]],state.employees)+'</div></div>';document.getElementById('employeeForm').onsubmit=async(event)=>{event.preventDefault();const f=new FormData(event.target);const body=Object.fromEntries(f);body.email=body.email||null;body.seniorityDate=new Date(body.seniorityDate+'T00:00:00Z').toISOString();try{await api('/employees',{method:'POST',body:JSON.stringify(body)});state.employees=[];await employees();}catch(e){showError(e);}};}
  async function coverages(){await ensureBase();const items=(await api('/coverages')).items||[];const options=state.employees.map(e=>'<option value="'+esc(e.id)+'">'+esc(e.name)+' · '+esc(e.employee_number)+'</option>').join('');view.innerHTML='<div class="panel"><h3>Nueva ausencia y cobertura</h3><form id="coverageForm"><label>Persona ausente<select name="absentEmployeeId" required>'+options+'</select></label><label>Motivo<input name="reason" required></label><label>Inicio<input name="startsAt" type="datetime-local" required></label><label>Fin<input name="endsAt" type="datetime-local" required></label><div id="competitionFields" class="wide hidden"><div class="notice">Al superar 5 días se abrirá concurso.</div><div class="split"><label>Fin de registro<input name="registrationEndsAt" type="datetime-local"></label><label>Fecha de examen<input name="examAt" type="datetime-local"></label></div></div><div class="wide"><button class="primary">Crear expediente</button></div></form></div><div class="panel"><h3>Expedientes</h3>'+table([['Folio',r=>esc(r.folio)],['Ausente',r=>esc(r.absent_employee_name)],['Periodo',r=>esc(r.starts_at)+'<br>'+esc(r.ends_at)],['Proceso',r=>badge(r.process_type)],['Estado',r=>badge(r.status)],['Acción',r=>'<button class="secondary" data-cancel="'+esc(r.id)+'">Cancelar</button>']],items)+'</div>';const form=document.getElementById('coverageForm');function duration(){const start=new Date(form.startsAt.value);const end=new Date(form.endsAt.value);const days=Math.floor((end-start)/86400000)+1;document.getElementById('competitionFields').classList.toggle('hidden',!(days>=6));return days;}form.startsAt.onchange=duration;form.endsAt.onchange=duration;form.onsubmit=async(event)=>{event.preventDefault();const f=new FormData(form);const days=duration();const body={absentEmployeeId:f.get('absentEmployeeId'),reason:f.get('reason'),startsAt:new Date(f.get('startsAt')).toISOString(),endsAt:new Date(f.get('endsAt')).toISOString(),source:'MANUAL'};if(days>=6){body.competition={registrationStartsAt:new Date().toISOString(),registrationEndsAt:new Date(f.get('registrationEndsAt')).toISOString(),examAt:new Date(f.get('examAt')).toISOString()};}try{await api('/coverages',{method:'POST',body:JSON.stringify(body)});await coverages();}catch(e){showError(e);}};document.querySelectorAll('[data-cancel]').forEach(button=>button.onclick=async()=>{const reason=prompt('Motivo de cancelación');if(!reason)return;try{await api('/coverages/'+button.dataset.cancel+'/cancel',{method:'POST',body:JSON.stringify({reason,cancelAbsence:false})});await coverages();}catch(e){showError(e);}});}
  async function approvals(){const items=(await api('/approvals')).items||[];view.innerHTML='<div class="panel"><h3>Aprobaciones</h3>'+table([['Folio',r=>esc(r.folio)],['Persona propuesta',r=>esc(r.proposed_employee)],['Proceso',r=>badge(r.process_type)],['Estado',r=>badge(r.status)],['Periodo',r=>esc(r.starts_at)+'<br>'+esc(r.ends_at)],['Acción',r=>r.status==='PENDING'?'<div class="actions"><button class="primary" data-approve="'+esc(r.id)+'">Aprobar</button><button class="danger" data-reject="'+esc(r.id)+'">Rechazar</button></div>':'—']],items)+'</div>';document.querySelectorAll('[data-approve],[data-reject]').forEach(button=>button.onclick=async()=>{const approved=button.dataset.approve;const id=approved||button.dataset.reject;const reason=prompt('Motivo de la decisión','Revisión completada');if(!reason)return;try{await api('/approvals/'+id+'/decide',{method:'POST',body:JSON.stringify({decision:approved?'APPROVED':'REJECTED',reason})});await approvals();}catch(e){showError(e);}});}
  async function rotations(){const items=(await api('/rotation-pools')).items||[];view.innerHTML='<div class="panel"><h3>Filas de rotación</h3>'+table([['Grupo',r=>esc(r.group_name)],['Movimiento',r=>esc(r.source_level)+' → '+esc(r.target_level)],['Posición',r=>esc(r.queue_position)],['Persona',r=>esc(r.employee_name)],['Disponibilidad',r=>badge(r.availability)],['Coberturas',r=>esc(r.times_selected)]],items)+'</div>';}
  async function competitions(){const items=(await api('/competitions')).items||[];view.innerHTML='<div class="panel"><h3>Concursos</h3>'+table([['Folio',r=>esc(r.folio)],['Estado',r=>badge(r.status)],['Registro',r=>esc(r.registration_ends_at)],['Examen',r=>esc(r.exam_at)],['Elegibles',r=>esc(r.eligible_count)],['No elegibles',r=>esc(r.ineligible_count)],['ID',r=>'<span class="code">'+esc(r.id)+'</span>']],items)+'</div>';}
  async function intake(){const drafts=(await api('/intake-drafts')).items||[];view.innerHTML='<div class="panel"><h3>Subir audio, imagen o documento</h3><form id="uploadForm"><label class="wide">Archivo<input name="file" type="file" accept="audio/*,image/jpeg,image/png,image/webp,application/pdf" required></label><div class="wide"><button class="primary">Procesar</button></div></form></div><div class="panel"><h3>Borradores para revisión</h3>'+table([['Fuente',r=>badge(r.source_type)],['Estado',r=>badge(r.status)],['Datos extraídos',r=>'<div class="code">'+esc(r.draft_json)+'</div>'],['Creado',r=>esc(r.created_at)]],drafts)+'</div>';document.getElementById('uploadForm').onsubmit=async(event)=>{event.preventDefault();const body=new FormData(event.target);try{await api('/attachments',{method:'POST',body,headers:{}});alert('Archivo recibido. La extracción aparecerá al terminar la cola.');await intake();}catch(e){showError(e);}};}
  async function configuration(){await ensureBase();const c=state.config;view.innerHTML='<div class="split"><div class="panel"><h3>Grupos</h3>'+table([['Nombre',r=>esc(r.name)],['ID',r=>'<span class="code">'+esc(r.id)+'</span>']],c.groups||[])+'</div><div class="panel"><h3>Niveles</h3>'+table([['Nombre',r=>esc(r.name)],['Número',r=>esc(r.level_number)],['Grupo',r=>esc(r.group_id)],['ID',r=>'<span class="code">'+esc(r.id)+'</span>']],c.levels||[])+'</div></div><div class="split"><div class="panel"><h3>Transiciones permitidas</h3>'+table([['Origen',r=>esc(r.source_level_id)],['Destino',r=>esc(r.target_level_id)]],c.transitions||[])+'</div><div class="panel"><h3>Requisitos</h3>'+table([['Nombre',r=>esc(r.name)],['Tipo',r=>badge(r.requirement_type)],['ID',r=>'<span class="code">'+esc(r.id)+'</span>']],c.requirements||[])+'</div></div>';}
  async function audit(){const items=(await api('/audit')).items||[];view.innerHTML='<div class="panel"><h3>Historial inmutable</h3>'+table([['Fecha',r=>esc(r.occurred_at)],['Entidad',r=>esc(r.entity_type)+'<br><span class="code">'+esc(r.entity_id)+'</span>'],['Acción',r=>badge(r.action)],['Actor',r=>esc(r.actor_type)+':'+esc(r.actor_id)],['Regla',r=>esc(r.rule_applied)],['Motivo',r=>esc(r.reason)]],items)+'</div>';}
  async function messages(){const items=(await api('/messages')).items||[];view.innerHTML='<div class="panel"><h3>Mensajes</h3>'+table([['Fecha',r=>esc(r.created_at)],['Canal',r=>badge(r.channel)],['Destinatario',r=>esc(r.recipient)],['Asunto',r=>esc(r.subject)],['Estado',r=>badge(r.status)],['Error',r=>esc(r.error_code)]],items)+'</div>';}
  const loaders={dashboard,employees,coverages,approvals,rotations,competitions,intake,configuration,audit,messages};
  async function load(page){document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));const label=(pages.find(p=>p[0]===page)||[])[1]||page;title.textContent=label;subtitle.textContent='YRAK Coberturas';view.innerHTML='<div class="panel">Cargando…</div>';try{await loaders[page]();}catch(e){showError(e);}}
  nav();load('dashboard');
})();
</script>
</body></html>`;
}
