export function adminUltimateHtml(): string {
  return `<!doctype html>
<html lang="es-MX">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>YRAK Coberturas</title>
  <style>
    :root{font-family:Inter,ui-sans-serif,system-ui,sans-serif;color:#142033;background:#f5f7fb}*{box-sizing:border-box}body{margin:0}header{background:#0f2742;color:white;padding:18px 24px;display:flex;justify-content:space-between;align-items:center}header h1{font-size:20px;margin:0}header small{opacity:.75}.layout{display:grid;grid-template-columns:220px 1fr;min-height:calc(100vh - 67px)}nav{background:#fff;border-right:1px solid #dfe5ec;padding:16px;display:flex;flex-direction:column;gap:6px}nav button{border:0;background:transparent;text-align:left;padding:11px 12px;border-radius:8px;cursor:pointer;color:#334155}nav button.active,nav button:hover{background:#e8f0f8;color:#0f2742;font-weight:700}main{padding:22px;overflow:auto}.view{display:none}.view.active{display:block}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:14px}.card{background:white;border:1px solid #e2e8f0;border-radius:12px;padding:16px;box-shadow:0 3px 12px rgba(15,39,66,.04)}.card h2,.card h3{margin-top:0}.metric{font-size:30px;font-weight:800;color:#0f2742}.muted{color:#64748b;font-size:13px}form{display:grid;gap:10px}label{font-size:12px;font-weight:700;color:#475569}input,select,textarea,button.action{width:100%;padding:10px;border:1px solid #cbd5e1;border-radius:7px;background:white}textarea{min-height:85px;resize:vertical}button.action{background:#0f5a8c;color:white;border:0;font-weight:700;cursor:pointer}button.danger{background:#9f2434}button.secondary{background:#475569}table{width:100%;border-collapse:collapse;font-size:13px}th,td{padding:9px;border-bottom:1px solid #e2e8f0;text-align:left;vertical-align:top}th{color:#475569;background:#f8fafc;position:sticky;top:0}.table-wrap{overflow:auto;max-height:480px}.toolbar{display:flex;gap:8px;align-items:center;margin-bottom:12px}.toolbar input,.toolbar select{max-width:280px}.status{padding:3px 7px;border-radius:99px;background:#e2e8f0;font-size:11px;white-space:nowrap}.notice{padding:10px;border-radius:8px;margin:10px 0;display:none}.notice.ok{display:block;background:#dcfce7;color:#166534}.notice.error{display:block;background:#fee2e2;color:#991b1b}.split{display:grid;grid-template-columns:minmax(300px,1fr) minmax(300px,1fr);gap:14px}pre{white-space:pre-wrap;background:#0f172a;color:#e2e8f0;padding:12px;border-radius:8px;max-height:420px;overflow:auto}@media(max-width:850px){.layout{grid-template-columns:1fr}nav{border-right:0;border-bottom:1px solid #ddd;flex-direction:row;overflow:auto}.split{grid-template-columns:1fr}}
  </style>
</head>
<body>
<header><div><h1>YRAK Coberturas</h1><small>Rotación, concursos y auditoría SUTERM</small></div><div id="session" class="muted" style="color:#dbeafe">Sesión protegida por Cloudflare Access</div></header>
<div class="layout">
<nav id="nav">
  <button data-view="summary" class="active">Resumen</button>
  <button data-view="employees">Personal</button>
  <button data-view="coverages">Coberturas</button>
  <button data-view="approvals">Aprobaciones</button>
  <button data-view="competitions">Concursos</button>
  <button data-view="intake">Bandeja IA</button>
  <button data-view="appeals">Inconformidades</button>
  <button data-view="configuration">Configuración</button>
  <button data-view="users">Usuarios</button>
  <button data-view="data">Datos</button>
  <button data-view="audit">Auditoría</button>
</nav>
<main>
<div id="notice" class="notice"></div>
<section id="summary" class="view active"><h2>Resumen operativo</h2><div class="grid" id="metrics"></div></section>

<section id="employees" class="view"><h2>Personal</h2><div class="split"><div class="card"><h3>Alta de persona</h3><form id="employee-form"><label>Número<input name="employeeNumber" required></label><label>Nombre<input name="name" required></label><label>Correo<input name="email" type="email"></label><label>Grupo ID<input name="groupId" required></label><label>Nivel base ID<input name="baseLevelId" required></label><label>Antigüedad<input name="seniorityDate" type="datetime-local" required></label><button class="action">Crear</button></form></div><div class="card"><h3>Directorio</h3><button class="action secondary" onclick="loadEmployees()">Actualizar</button><div class="table-wrap"><table><thead><tr><th>Número</th><th>Nombre</th><th>Grupo</th><th>Nivel</th><th>Activo</th></tr></thead><tbody id="employees-body"></tbody></table></div></div></div></section>

<section id="coverages" class="view"><h2>Coberturas</h2><div class="split"><div class="card"><h3>Nueva ausencia</h3><form id="coverage-form"><label>Persona ausente ID<input name="absentEmployeeId" required></label><label>Motivo<textarea name="reason" required></textarea></label><label>Inicio<input name="startsAt" type="datetime-local" required></label><label>Fin<input name="endsAt" type="datetime-local" required></label><label>Datos de concurso para 6+ días (JSON)<textarea name="competition" placeholder='{"registrationStartsAt":"...","registrationEndsAt":"...","examAt":"..."}'></textarea></label><button class="action">Crear expediente</button></form></div><div class="card"><h3>Expedientes</h3><button class="action secondary" onclick="loadCoverages()">Actualizar</button><div class="table-wrap"><table><thead><tr><th>Folio</th><th>Ausente</th><th>Días</th><th>Proceso</th><th>Estado</th><th>ID</th></tr></thead><tbody id="coverages-body"></tbody></table></div></div></div><div class="card" style="margin-top:14px"><h3>Acciones sobre expediente</h3><div class="grid"><form id="coverage-detail-form"><label>Expediente ID<input name="id" required></label><button class="action secondary">Consultar</button></form><form id="coverage-cancel-form"><label>Expediente ID<input name="id" required></label><label>Motivo<input name="reason" required></label><button class="action danger">Cancelar antes de iniciar</button></form><form id="coverage-complete-form"><label>Expediente ID<input name="id" required></label><label>Motivo<input name="reason" required></label><button class="action">Terminar y regresar</button></form></div><pre id="coverage-detail"></pre></div></section>

<section id="approvals" class="view"><h2>Aprobaciones</h2><div class="card"><form id="approval-form"><div class="grid"><label>Aprobación ID<input name="id" required></label><label>Decisión<select name="decision"><option>APPROVED</option><option>REJECTED</option></select></label><label>Motivo<input name="reason" required></label></div><button class="action">Registrar decisión</button></form></div></section>

<section id="competitions" class="view"><h2>Concursos</h2><div class="split"><div class="card"><h3>Consultar concurso</h3><form id="competition-detail-form"><label>Concurso ID<input name="id" required></label><button class="action secondary">Consultar</button></form><pre id="competition-detail"></pre></div><div class="card"><h3>Registrar examen</h3><form id="score-form"><label>Concurso ID<input name="competitionId" required></label><label>Persona ID<input name="employeeId" required></label><label>Calificación<input name="examScore" type="number" min="0" max="100" step=".01" required></label><label>Sección crítica<input name="criticalSectionScore" type="number" min="0" max="100" step=".01"></label><button class="action">Registrar</button></form><hr><form id="finalize-form"><label>Concurso ID<input name="id" required></label><button class="action">Calcular ranking provisional</button></form></div></div></section>

<section id="intake" class="view"><h2>Bandeja IA</h2><div class="split"><div class="card"><h3>Subir evidencia</h3><form id="attachment-form"><input name="file" type="file" accept="audio/*,image/jpeg,image/png,image/webp,application/pdf" required><button class="action">Procesar</button></form></div><div class="card"><h3>Borradores pendientes</h3><button class="action secondary" onclick="loadDrafts()">Actualizar</button><pre id="drafts"></pre></div></div><div class="card" style="margin-top:14px"><h3>Confirmar borrador</h3><form id="draft-approve-form"><div class="grid"><label>Borrador ID<input name="id" required></label><label>Persona ausente ID<input name="absentEmployeeId" required></label><label>Inicio<input name="startsAt" type="datetime-local" required></label><label>Fin<input name="endsAt" type="datetime-local" required></label></div><label>Motivo<textarea name="reason" required></textarea></label><label>Concurso JSON, solo 6+ días<textarea name="competition"></textarea></label><button class="action">Confirmar y crear</button></form></div></section>

<section id="appeals" class="view"><h2>Inconformidades</h2><div class="split"><div class="card"><h3>Presentar</h3><form id="appeal-form"><label>Concurso ID<input name="competitionId" required></label><label>Persona ID<input name="employeeId" required></label><label>Motivo<textarea name="reason" minlength="10" required></textarea></label><button class="action">Presentar</button></form></div><div class="card"><h3>Resolver</h3><form id="appeal-decide-form"><label>Inconformidad ID<input name="id" required></label><label>Decisión<select name="decision"><option>UPHELD</option><option>DISMISSED</option></select></label><label>Motivo<textarea name="reason" minlength="10" required></textarea></label><button class="action">Resolver con segundo actor</button></form></div></div><div class="card" style="margin-top:14px"><button class="action secondary" onclick="loadAppeals()">Actualizar lista</button><pre id="appeals-list"></pre></div></section>

<section id="configuration" class="view"><h2>Configuración</h2><div class="grid"><div class="card"><h3>Grupo</h3><form id="group-form"><label>Nombre<input name="name" required></label><label>Descripción<input name="description"></label><button class="action">Crear</button></form></div><div class="card"><h3>Nivel</h3><form id="level-form"><label>Grupo ID<input name="groupId" required></label><label>Número<input name="levelNumber" type="number" required></label><label>Nombre<input name="name" required></label><label>Orden<input name="rankOrder" type="number" required></label><button class="action">Crear</button></form></div><div class="card"><h3>Transición</h3><form id="transition-form"><label>Grupo ID<input name="groupId" required></label><label>Nivel origen<input name="sourceLevelId" required></label><label>Nivel destino<input name="targetLevelId" required></label><button class="action">Autorizar</button></form></div><div class="card"><h3>Canal de correo</h3><form id="email-channel-form"><label>Dirección<input name="inboundAddress" type="email" required></label><button class="action">Registrar</button></form></div></div><div class="card" style="margin-top:14px"><h3>Política</h3><form id="policy-form"><div class="grid"><label>Conteo<select name="dayCountingMode"><option>CALENDAR_DAYS</option><option>WORKING_DAYS</option><option>SHIFTS</option></select></label><label>Mínimo examen<input name="defaultMinimumExamScore" type="number" min="0" max="100" value="70"></label></div><label>Desempates JSON<textarea name="defaultTieBreakers">[{"type":"SENIORITY"},{"type":"EMPLOYEE_ID"}]</textarea></label><button class="action">Guardar política</button></form></div></section>

<section id="users" class="view"><h2>Usuarios</h2><div class="split"><div class="card"><h3>Alta</h3><form id="user-form"><label>Subject de Access<input name="externalSubject" required></label><label>Correo<input name="email" type="email" required></label><label>Nombre<input name="displayName" required></label><label>Empleado ID opcional<input name="employeeId"></label><label>Roles, separados por coma<input name="roles" placeholder="HR,SUPERVISOR" required></label><label>Grupos, separados por coma<input name="groupIds"></label><button class="action">Crear usuario</button></form></div><div class="card"><h3>Registrados</h3><button class="action secondary" onclick="loadUsers()">Actualizar</button><pre id="users-list"></pre></div></div></section>

<section id="data" class="view"><h2>Datos y exportaciones</h2><div class="grid"><div class="card"><h3>Importar personal CSV</h3><form id="csv-preview-form"><input name="file" type="file" accept=".csv,text/csv" required><button class="action">Previsualizar</button></form><pre id="csv-preview"></pre></div><div class="card"><h3>Exportaciones</h3><a href="/api/v1/exports/employees.csv">Descargar personal</a><br><br><a href="/api/v1/exports/coverages.csv">Descargar coberturas</a></div><div class="card"><h3>Carga masiva JSON</h3><form id="bulk-form"><label>Tipo<select name="type"><option value="requirements">Requisitos</option><option value="employee-requirements">Cumplimiento</option><option value="shifts">Turnos</option></select></label><textarea name="rows" placeholder='[{"name":"Curso..."}]' required></textarea><button class="action">Importar</button></form></div></div></section>

<section id="audit" class="view"><h2>Auditoría</h2><div class="card"><form id="audit-form"><div class="grid"><label>Tipo de entidad<input name="entityType" required></label><label>Entidad ID<input name="entityId" required></label></div><button class="action secondary">Consultar</button></form><pre id="audit-result"></pre></div></section>
</main></div>
<script>
const api='/api/v1';
function key(){return crypto.randomUUID()}
function iso(v){return v?new Date(v).toISOString():undefined}
function values(form){return Object.fromEntries(new FormData(form).entries())}
function show(message,error=false){const n=document.getElementById('notice');n.textContent=message;n.className='notice '+(error?'error':'ok');setTimeout(()=>{n.className='notice'},5500)}
async function call(path,options={}){const headers=new Headers(options.headers||{});if(options.body&&!(options.body instanceof FormData)){headers.set('content-type','application/json');options.body=JSON.stringify(options.body)}if(options.method&&options.method!=='GET')headers.set('idempotency-key',key());const response=await fetch(api+path,{...options,headers});const text=await response.text();let data;try{data=text?JSON.parse(text):{}}catch{data={raw:text}}if(!response.ok)throw new Error((data&&data.message)||data.error||('HTTP '+response.status));return data}
function renderRows(id,rows,columns){document.getElementById(id).innerHTML=rows.map(r=>'<tr>'+columns.map(c=>'<td>'+String(r[c]??'')+'</td>').join('')+'</tr>').join('')}
async function loadSummary(){try{const d=await call('/dashboard');document.getElementById('metrics').innerHTML=[['Coberturas activas',d.activeCoverages],['Concursos abiertos',d.openCompetitions],['Requisitos pendientes',d.requirementIssues],['Aprobaciones',d.pendingApprovals]].map(x=>'<div class="card"><div class="muted">'+x[0]+'</div><div class="metric">'+x[1]+'</div></div>').join('')}catch(e){show(e.message,true)}}
async function loadEmployees(){try{const d=await call('/employees');renderRows('employees-body',d.items||[],['employee_number','name','group_id','base_level_id','active'])}catch(e){show(e.message,true)}}
async function loadCoverages(){try{const d=await call('/coverages');renderRows('coverages-body',d.items||[],['folio','absent_employee_name','duration_days','process_type','status','id'])}catch(e){show(e.message,true)}}
async function loadDrafts(){try{document.getElementById('drafts').textContent=JSON.stringify(await call('/intake-drafts'),null,2)}catch(e){show(e.message,true)}}
async function loadAppeals(){try{document.getElementById('appeals-list').textContent=JSON.stringify(await call('/appeals'),null,2)}catch(e){show(e.message,true)}}
async function loadUsers(){try{document.getElementById('users-list').textContent=JSON.stringify(await call('/users'),null,2)}catch(e){show(e.message,true)}}
document.getElementById('nav').addEventListener('click',e=>{if(e.target.tagName!=='BUTTON')return;document.querySelectorAll('nav button').forEach(b=>b.classList.remove('active'));e.target.classList.add('active');document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.getElementById(e.target.dataset.view).classList.add('active')});
function bind(id,handler){document.getElementById(id).addEventListener('submit',async e=>{e.preventDefault();try{await handler(e.target);show('Operación completada')}catch(err){show(err.message,true)}})}
bind('employee-form',async f=>{const v=values(f);await call('/employees',{method:'POST',body:{employeeNumber:v.employeeNumber,name:v.name,email:v.email||null,groupId:v.groupId,baseLevelId:v.baseLevelId,seniorityDate:iso(v.seniorityDate)}});f.reset();loadEmployees()});
bind('coverage-form',async f=>{const v=values(f);const body={absentEmployeeId:v.absentEmployeeId,reason:v.reason,startsAt:iso(v.startsAt),endsAt:iso(v.endsAt),source:'MANUAL'};if(v.competition)body.competition=JSON.parse(v.competition);const d=await call('/coverages',{method:'POST',body});document.getElementById('coverage-detail').textContent=JSON.stringify(d,null,2);loadCoverages()});
bind('coverage-detail-form',async f=>{const v=values(f);document.getElementById('coverage-detail').textContent=JSON.stringify(await call('/coverages/'+encodeURIComponent(v.id)),null,2)});
bind('coverage-cancel-form',async f=>{const v=values(f);await call('/coverages/'+encodeURIComponent(v.id)+'/cancel',{method:'POST',body:{reason:v.reason,cancelAbsence:false}});loadCoverages()});
bind('coverage-complete-form',async f=>{const v=values(f);await call('/coverages/'+encodeURIComponent(v.id)+'/complete-early',{method:'POST',body:{reason:v.reason,returnedAt:new Date().toISOString()}});loadCoverages()});
bind('approval-form',async f=>{const v=values(f);await call('/approvals/'+encodeURIComponent(v.id)+'/decide',{method:'POST',body:{decision:v.decision,reason:v.reason}});loadCoverages()});
bind('competition-detail-form',async f=>{const v=values(f);document.getElementById('competition-detail').textContent=JSON.stringify(await call('/competitions/'+encodeURIComponent(v.id)),null,2)});
bind('score-form',async f=>{const v=values(f);const body={employeeId:v.employeeId,examScore:Number(v.examScore)};if(v.criticalSectionScore)body.criticalSectionScore=Number(v.criticalSectionScore);await call('/competitions/'+encodeURIComponent(v.competitionId)+'/scores',{method:'POST',body})});
bind('finalize-form',async f=>{const v=values(f);document.getElementById('competition-detail').textContent=JSON.stringify(await call('/competitions/'+encodeURIComponent(v.id)+'/finalize',{method:'POST',body:{}}),null,2)});
bind('attachment-form',async f=>{const fd=new FormData(f);const d=await call('/attachments',{method:'POST',body:fd});show('Archivo recibido: '+d.attachmentId);loadDrafts()});
bind('draft-approve-form',async f=>{const v=values(f);const body={absentEmployeeId:v.absentEmployeeId,reason:v.reason,startsAt:iso(v.startsAt),endsAt:iso(v.endsAt)};if(v.competition)body.competition=JSON.parse(v.competition);await call('/intake-drafts/'+encodeURIComponent(v.id)+'/approve',{method:'POST',body});loadDrafts();loadCoverages()});
bind('appeal-form',async f=>{const v=values(f);await call('/competitions/'+encodeURIComponent(v.competitionId)+'/appeals',{method:'POST',body:{employeeId:v.employeeId,reason:v.reason}});loadAppeals()});
bind('appeal-decide-form',async f=>{const v=values(f);await call('/appeals/'+encodeURIComponent(v.id)+'/decide',{method:'POST',body:{decision:v.decision,reason:v.reason}});loadAppeals()});
bind('group-form',async f=>{const v=values(f);await call('/groups',{method:'POST',body:v})});
bind('level-form',async f=>{const v=values(f);await call('/levels',{method:'POST',body:{groupId:v.groupId,levelNumber:Number(v.levelNumber),name:v.name,rankOrder:Number(v.rankOrder)}})});
bind('transition-form',async f=>{const v=values(f);await call('/level-transitions',{method:'POST',body:v})});
bind('email-channel-form',async f=>{const v=values(f);await call('/email-channels',{method:'POST',body:v})});
bind('policy-form',async f=>{const v=values(f);await call('/policy',{method:'PUT',body:{dayCountingMode:v.dayCountingMode,justifiedUnavailabilityKeepsPosition:true,voluntaryRejectionConsumesTurn:true,cancellationBeforeStartConsumesTurn:false,defaultMinimumExamScore:Number(v.defaultMinimumExamScore),defaultTieBreakers:JSON.parse(v.defaultTieBreakers)}})});
bind('user-form',async f=>{const v=values(f);await call('/users',{method:'POST',body:{externalSubject:v.externalSubject,email:v.email,displayName:v.displayName,employeeId:v.employeeId||null,roles:v.roles.split(',').map(x=>x.trim()).filter(Boolean),groupIds:v.groupIds.split(',').map(x=>x.trim()).filter(Boolean)}});loadUsers()});
bind('csv-preview-form',async f=>{const fd=new FormData(f);document.getElementById('csv-preview').textContent=JSON.stringify(await call('/imports/employees/preview',{method:'POST',body:fd}),null,2)});
bind('bulk-form',async f=>{const v=values(f);await call('/bulk/'+v.type,{method:'POST',body:{rows:JSON.parse(v.rows)}})});
bind('audit-form',async f=>{const v=values(f);document.getElementById('audit-result').textContent=JSON.stringify(await call('/audit?entityType='+encodeURIComponent(v.entityType)+'&entityId='+encodeURIComponent(v.entityId)),null,2)});
loadSummary();loadEmployees();loadCoverages();
</script>
</body></html>`;
}
