import { Hono } from 'hono';
import { z } from 'zod';
import { zValidator } from '@hono/zod-validator';
import type { AppBindings } from '../env.js';
import { assertGroupAccess,requireRoles } from '../middleware.js';
import { evaluateCompetitionCandidates,calculateCompetitionRanking } from '../services/competition-service.js';
import { AuditWriter } from '@yrak/audit';

export const competitionRoutes=new Hono<AppBindings>();
competitionRoutes.post('/cases/:caseId/evaluate',requireRoles('ADMIN','HR','COMMITTEE'),async c=>{const u=c.get('user');const row=await c.env.DB.prepare(`SELECT * FROM coverage_cases WHERE id=? AND organization_id=?`).bind(c.req.param('caseId'),u.organizationId).first<any>();if(!row)return c.json({error:'COVERAGE_NOT_FOUND'},404);await assertGroupAccess(c,row.group_id);return c.json(await evaluateCompetitionCandidates(c.env,u,row,c.get('correlationId')));});
competitionRoutes.put('/:competitionId/candidates/:candidateId/score',requireRoles('ADMIN','HR','COMMITTEE'),zValidator('json',z.object({score:z.number().min(0).max(100),reason:z.string().min(1).default('CAPTURE')})),async c=>{const u=c.get('user'),i=c.req.valid('json');const row=await c.env.DB.prepare(`SELECT cc.id,cc.exam_score,cv.organization_id FROM competition_candidates cc JOIN competitions cp ON cp.id=cc.competition_id JOIN coverage_cases cv ON cv.id=cp.coverage_case_id WHERE cc.id=? AND cp.id=? AND cv.organization_id=?`).bind(c.req.param('candidateId'),c.req.param('competitionId'),u.organizationId).first<{id:string;exam_score:number|null;organization_id:string}>();if(!row)return c.json({error:'CANDIDATE_NOT_FOUND'},404);await c.env.DB.prepare(`UPDATE competition_candidates SET exam_score=? WHERE id=?`).bind(i.score,row.id).run();await c.env.DB.prepare(`INSERT INTO competition_score_revisions(id,candidate_id,previous_score,new_score,reason,requested_by,approved_by,approved_at) VALUES(?,?,?,?,?,?,?,datetime('now'))`).bind(crypto.randomUUID(),row.id,row.exam_score,i.score,i.reason,u.id,u.id).run();await new AuditWriter(c.env.DB).append({organizationId:u.organizationId,actorId:u.id,actorRole:u.role,entityType:'COMPETITION_CANDIDATE',entityId:row.id,action:'EXAM_SCORE_RECORDED',previousValue:{score:row.exam_score},newValue:{score:i.score},reason:i.reason,correlationId:c.get('correlationId')});return c.json({updated:true});});
competitionRoutes.post('/:competitionId/rank',requireRoles('ADMIN','HR','COMMITTEE'),async c=>c.json({ranking:await calculateCompetitionRanking(c.env,c.get('user'),c.req.param('competitionId'),c.get('correlationId'))}));
competitionRoutes.post('/:competitionId/award',requireRoles('ADMIN','HR','COMMITTEE'),async c=>{const u=c.get('user');const row=await c.env.DB.prepare(`SELECT cp.id,cv.id coverage_case_id,cv.organization_id,cv.group_id,cv.target_level_id,cv.starts_on,cv.ends_on,cc.employee_id,e.base_level_id FROM competitions cp JOIN coverage_cases cv ON cv.id=cp.coverage_case_id JOIN competition_candidates cc ON cc.competition_id=cp.id AND cc.rank=1 JOIN employees e ON e.id=cc.employee_id WHERE cp.id=? AND cv.organization_id=?`).bind(c.req.param('competitionId'),u.organizationId).first<any>();if(!row)return c.json({error:'PROVISIONAL_WINNER_NOT_FOUND'},409);await assertGroupAccess(c,row.group_id);const assignmentId=crypto.randomUUID();await c.env.DB.batch([c.env.DB.prepare(`INSERT INTO temporary_assignments(id,coverage_case_id,employee_id,base_level_id,target_level_id,starts_on,ends_on,status) VALUES(?,?,?,?,?,?,?,'SCHEDULED')`).bind(assignmentId,row.coverage_case_id,row.employee_id,row.base_level_id,row.target_level_id,row.starts_on,row.ends_on),c.env.DB.prepare(`UPDATE competitions SET status='AWARDED',approved_by=?,approved_at=datetime('now'),version=version+1 WHERE id=?`).bind(u.id,row.id),c.env.DB.prepare(`UPDATE coverage_cases SET status='SCHEDULED',version=version+1,updated_at=datetime('now') WHERE id=?`).bind(row.coverage_case_id)]);if(c.env.COVERAGE_WORKFLOW)await c.env.COVERAGE_WORKFLOW.create({id:`coverage-${row.coverage_case_id}`,params:{coverageCaseId:row.coverage_case_id,startsOn:row.starts_on,endsOn:row.ends_on}});return c.json({awarded:true,employeeId:row.employee_id,assignmentId});});
